#!/usr/bin/env python3
"""Fetch publications from Google Scholar and write _data/publications.yml."""

from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path

import yaml
from scholarly import scholarly

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "_config.yml"
OUTPUT_PATH = ROOT / "_data" / "publications.yml"

# Google Scholar often blocks cloud IPs (including GitHub Actions). Retries help locally;
# in CI we usually keep the last committed publications.yml when fetch fails.
MAX_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 45


class ScholarFetchError(Exception):
    """Raised when Scholar data could not be retrieved after retries."""


def read_user_id() -> str:
    user_id = os.environ.get("SCHOLAR_USER_ID", "").strip()
    if user_id:
        return user_id
    if not CONFIG_PATH.exists():
        print("SCHOLAR_USER_ID not set and _config.yml not found", file=sys.stderr)
        sys.exit(1)
    text = CONFIG_PATH.read_text(encoding="utf-8")
    match = re.search(r'^scholar_user_id:\s*["\']?([^"\'#\s]+)', text, re.MULTILINE)
    if not match:
        print("scholar_user_id not found in _config.yml", file=sys.stderr)
        sys.exit(1)
    return match.group(1).strip()


def normalize_title(title: str) -> str:
    title = title.replace("\u2010", "-").replace("\u2011", "-").replace("\u2013", "-")
    title = title.replace("\u2014", "-").replace("\u2212", "-")
    return re.sub(r"\s+", " ", title.strip().lower().rstrip("."))


def format_authors(author_str: str) -> str:
    if not author_str:
        return ""
    parts = [part.strip() for part in author_str.split(" and ")]
    if len(parts) == 1:
        return parts[0]
    return ", ".join(parts[:-1]) + ", & " + parts[-1]


def venue_from_bib(bib: dict) -> str:
    for key in ("journal", "conference", "booktitle", "venue", "publisher"):
        value = bib.get(key)
        if value:
            return str(value).strip()
    citation = bib.get("citation")
    if citation:
        return re.sub(r",\s*\d{4}\s*$", "", str(citation).strip())
    return ""


def parse_year(raw) -> int | None:
    if raw is None or raw == "":
        return None
    try:
        return int(str(raw).strip())
    except ValueError:
        return None


def publication_url(pub: dict, bib: dict) -> str:
    for key in ("pub_url", "eprint_url"):
        value = pub.get(key)
        if value:
            return str(value).strip()
    for key in ("url", "eprint", "doi"):
        value = bib.get(key)
        if value:
            value = str(value).strip()
            if value.startswith("10."):
                return f"https://doi.org/{value}"
            return value
    return ""


def fetch_publications(user_id: str) -> list[dict]:
    author = scholarly.search_author_id(user_id)
    scholarly.fill(author, sections=["publications"])

    publications: list[dict] = []
    for pub in author.get("publications", []):
        scholarly.fill(pub)
        bib = pub.get("bib", {})
        title = str(bib.get("title", "")).strip().rstrip(".")
        if not title:
            continue
        entry = {
            "title": title,
            "title_key": normalize_title(title),
            "authors": format_authors(str(bib.get("author", "")).strip()),
            "venue": venue_from_bib(bib),
            "year": parse_year(bib.get("pub_year")),
            "url": publication_url(pub, bib),
        }
        publications.append(entry)

    publications.sort(key=lambda p: (p["year"] or 0, p["title"]), reverse=True)
    return publications


def fetch_with_retries(user_id: str) -> list[dict]:
    last_error: Exception | None = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            print(f"Attempt {attempt}/{MAX_ATTEMPTS}...")
            return fetch_publications(user_id)
        except Exception as exc:
            last_error = exc
            print(f"Attempt {attempt} failed: {exc}", file=sys.stderr)
            if attempt < MAX_ATTEMPTS:
                print(f"Retrying in {RETRY_DELAY_SECONDS}s...", file=sys.stderr)
                time.sleep(RETRY_DELAY_SECONDS)
    raise ScholarFetchError(str(last_error)) from last_error


def existing_publications_path() -> bool:
    if not OUTPUT_PATH.exists():
        return False
    text = OUTPUT_PATH.read_text(encoding="utf-8")
    return any(line.strip().startswith("- title:") for line in text.splitlines())


def write_publications(publications: list[dict]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/fetch_scholar.py — do not edit by hand.\n"
        "# Re-run locally or via .github/workflows/update-scholar.yml\n"
    )
    body = yaml.dump(
        publications,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )
    OUTPUT_PATH.write_text(header + body, encoding="utf-8")
    print(f"Wrote {len(publications)} publications to {OUTPUT_PATH}")


def main() -> None:
    user_id = read_user_id()
    print(f"Fetching publications for Scholar user {user_id}...")

    try:
        publications = fetch_with_retries(user_id)
    except ScholarFetchError as exc:
        print(
            "\nCould not fetch from Google Scholar (common on GitHub Actions datacenter IPs).",
            file=sys.stderr,
        )
        print(f"Reason: {exc}", file=sys.stderr)
        if existing_publications_path():
            print(
                f"Keeping existing {OUTPUT_PATH} — site build is unaffected.",
                file=sys.stderr,
            )
            sys.exit(0)
        print(
            "No existing publications.yml found. Run this script locally once, then commit.",
            file=sys.stderr,
        )
        sys.exit(1)

    if not publications:
        print("No publications returned; refusing to overwrite.", file=sys.stderr)
        sys.exit(1)

    write_publications(publications)


if __name__ == "__main__":
    main()
